const fs = require("fs/promises");
const {
  PDFDocument,
  StandardFonts,
  rgb,
} = require("pdf-lib");
const { findLayoutMatch } = require("./annotationGenerator");

const TYPE_COLORS = {
  underline: rgb(0.13, 0.55, 0.13),
  strikethrough: rgb(0.8, 0.1, 0.1),
  box: rgb(0.85, 0.55, 0),
  comment: rgb(0.2, 0.4, 0.8),
};

// Highlight color depends on the rubric-point STATUS, not the
// annotation type (type is always "highlight" for all three) — this
// is the border/marker-number color, kept fully opaque so it's
// legible against the page.
const STATUS_COLORS = {
  correct: rgb(0.13, 0.55, 0.13), // green
  partial: rgb(0.85, 0.55, 0), // amber
  incorrect: rgb(0.8, 0.1, 0.1), // red
};

// The FILL is the same colors but drawn translucent, like a real
// highlighter pen — legible text underneath, nothing struck through
// or covered.
const HIGHLIGHT_FILL_OPACITY = 0.28;

const CHAR_REPLACEMENTS = {
  "\u2018": "'",
  "\u2019": "'",
  "\u201C": '"',
  "\u201D": '"',
  "\u2013": "-",
  "\u2014": "-",
  "\u2026": "...",
  "\u00A0": " ",
  "\u2022": "*",
  "\u00B1": "+",
  "\u2248": "~",
  "\u2260": "=",
  "\u2264": "<",
  "\u2265": ">",
  "₹": "Rs",
};

function sanitizeForPDF(text) {
  if (!text) {
    return "";
  }

  let output = "";

  for (const character of String(text)) {
    if (CHAR_REPLACEMENTS[character]) {
      output += CHAR_REPLACEMENTS[character];
    } else if (
      character.codePointAt(0) <= 0xff
    ) {
      output += character;
    } else {
      output += "?";
    }
  }

  return output;
}

function resolveAnnotation(annotation, pages) {
  /*
   * If coordinates were already generated by OCR,
   * use them directly.
   */
  if (
    annotation.pageNumber != null &&
    annotation.x != null &&
    annotation.y != null
  ) {
    return annotation;
  }

  // Falls back to the SAME multi-line-aware, confidence-gated matcher
  // used at grading time (findLayoutMatch), instead of a separate
  // one-off substring check. The old local version here matched on
  // `text.includes(target) || target.includes(text)` against single
  // blocks only — for a manually-added annotation whose anchor text
  // spans more than one physical line, that either failed to match
  // at all or matched only the first line and clipped the mark short
  // of the full text, same bug class fixed in annotationGenerator.
  // Reusing findLayoutMatch means a fix there also fixes export.
  if (!annotation.anchorText) {
    return null;
  }

  const match = findLayoutMatch(
    annotation.anchorText,
    pages
  );

  if (!match?.bbox) {
    return null;
  }

  const [x1, y1, x2, y2] = match.bbox;

  return {
    ...annotation,
    pageNumber: match.pageNumber,
    x: x1,
    y: y1,
    width: x2 - x1,
    height: y2 - y1,
  };
}

async function buildAnnotatedPDF(
  originalPdfPath,
  studentAnswerText,
  studentAnswerLayout,
  annotations
) {
  /*
   * IMPORTANT:
   *
   * We load the ORIGINAL uploaded student PDF.
   *
   * We do NOT create a replacement PDF containing
   * the OCR text.
   */
  const originalBytes =
    await fs.readFile(
      originalPdfPath
    );

  const pdfDoc =
    await PDFDocument.load(
      originalBytes
    );

  const pages = pdfDoc.getPages();

  const font =
    await pdfDoc.embedFont(
      StandardFonts.Helvetica
    );

  const boldFont =
    await pdfDoc.embedFont(
      StandardFonts.HelveticaBold
    );

  const markers = [];

  let markerCounter = 0;

  for (const rawAnnotation of annotations) {
    const annotation =
      rawAnnotation.toObject
        ? rawAnnotation.toObject()
        : rawAnnotation;

    const resolved =
      resolveAnnotation(
        annotation,
        studentAnswerLayout
      );

    /*
     * If we cannot locate the annotation
     * on the original page, don't invent a
     * random position. Put it on the feedback page.
     */
    if (
      !resolved ||
      resolved.pageNumber == null ||
      resolved.x == null ||
      resolved.y == null
    ) {
      markerCounter += 1;

      markers.push({
        number: markerCounter,
        note: annotation.note || "",
        type: "comment",
      });

      continue;
    }

    const pageIndex =
      Number(resolved.pageNumber) - 1;

    if (
      pageIndex < 0 ||
      pageIndex >= pages.length
    ) {
      continue;
    }

    const page =
      pages[pageIndex];

    const {
      width: pageWidth,
      height: pageHeight,
    } = page.getSize();

    /*
     * OCR coordinates:
     *
     * [x1, y1, x2, y2]
     *
     * normalized 0-1000
     * top-left origin
     *
     * pdf-lib:
     *
     * points
     * bottom-left origin
     */
    const x =
      (Number(resolved.x) / 1000) *
      pageWidth;

    const boxWidth =
      Math.max(
        8,
        (Number(resolved.width || 0) /
          1000) *
          pageWidth
      );

    const boxHeight =
      Math.max(
        8,
        (Number(resolved.height || 0) /
          1000) *
          pageHeight
      );

    const topY =
      (Number(resolved.y) / 1000) *
      pageHeight;

    const y =
      pageHeight -
      topY -
      boxHeight;

    const color =
      (annotation.type === "highlight"
        ? STATUS_COLORS[annotation.status]
        : null) ||
      TYPE_COLORS[
        annotation.type
      ] ||
      TYPE_COLORS.comment;

    /*
     * Draw the annotation directly
     * over the ORIGINAL handwriting.
     */
    if (annotation.type === "highlight") {
      // Non-destructive: a translucent colored box over the region,
      // like a highlighter pen. Never covers/obscures the student's
      // actual handwriting strokes, and nothing is drawn THROUGH the
      // text (unlike the old strikethrough behavior).
      page.drawRectangle({
        x: x - 2,
        y: y - 2,
        width: boxWidth + 4,
        height: boxHeight + 4,
        color,
        opacity: HIGHLIGHT_FILL_OPACITY,
        borderColor: color,
        borderWidth: 1,
        borderOpacity: 0.9,
      });
    } else if (
      annotation.type ===
      "strikethrough"
    ) {
      page.drawLine({
        start: {
          x,
          y:
            y +
            boxHeight / 2,
        },

        end: {
          x:
            x +
            boxWidth,

          y:
            y +
            boxHeight / 2,
        },

        thickness: 2,
        color,
        opacity: 0.9,
      });
    } else if (
      annotation.type === "box"
    ) {
      page.drawRectangle({
        x: x - 2,
        y: y - 2,
        width: boxWidth + 4,
        height: boxHeight + 4,
        borderColor: color,
        borderWidth: 2,
        opacity: 0.9,
      });
    } else {
      page.drawLine({
        start: {
          x,
          y: y - 2,
        },

        end: {
          x:
            x +
            boxWidth,

          y: y - 2,
        },

        thickness: 2,
        color,
        opacity: 0.9,
      });
    }

    /*
     * Number the annotation so the teacher can
     * connect it to the feedback page.
     */
    markerCounter += 1;

    markers.push({
      number: markerCounter,
      note: annotation.note || "",
      type: annotation.type,
      status: annotation.status || null,
    });

    page.drawText(
      String(markerCounter),
      {
        x: Math.min(
          x +
            boxWidth +
            3,
          pageWidth - 15
        ),

        y: Math.min(
          y +
            boxHeight +
            3,
          pageHeight - 12
        ),

        size: 8,
        font: boldFont,
        color,
      }
    );
  }

  /*
   * Add feedback on NEW page(s).
   *
   * The original answer pages remain untouched
   * except for the visual annotation overlays.
   */
  let feedbackPage =
    pdfDoc.addPage([
      595.28,
      841.89,
    ]);

  let cursorY = 790;

  const margin = 45;

  feedbackPage.drawText(
    "GradeSense - Corrections & Feedback",
    {
      x: margin,
      y: cursorY,
      size: 16,
      font: boldFont,
    }
  );

  cursorY -= 30;

  if (markers.length === 0) {
    feedbackPage.drawText(
      "No annotations were generated.",
      {
        x: margin,
        y: cursorY,
        size: 11,
        font,
      }
    );
  }

  for (const marker of markers) {
    const note =
      sanitizeForPDF(
        `${marker.number}. ${marker.note}`
      );

    const color =
      (marker.type === "highlight"
        ? STATUS_COLORS[marker.status]
        : null) ||
      TYPE_COLORS[
        marker.type
      ] ||
      TYPE_COLORS.comment;

    const lines =
      wrapText(
        note,
        font,
        10,
        500
      );

    for (const line of lines) {
      if (cursorY < 55) {
        feedbackPage =
          pdfDoc.addPage([
            595.28,
            841.89,
          ]);

        cursorY = 790;
      }

      feedbackPage.drawText(
        line,
        {
          x: margin,
          y: cursorY,
          size: 10,
          font,
          color,
        }
      );

      cursorY -= 15;
    }

    cursorY -= 7;
  }

  return pdfDoc.save();
}

function wrapText(
  text,
  font,
  size,
  maxWidth
) {
  const words =
    text.split(/\s+/);

  const lines = [];

  let line = "";

  for (const word of words) {
    const candidate =
      line
        ? `${line} ${word}`
        : word;

    if (
      font.widthOfTextAtSize(
        candidate,
        size
      ) <= maxWidth
    ) {
      line = candidate;
    } else {
      if (line) {
        lines.push(line);
      }

      line = word;
    }
  }

  if (line) {
    lines.push(line);
  }

  return lines;
}

module.exports = {
  buildAnnotatedPDF,
};